spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kamis
    username: kamis-mysql
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    com.kamis: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG

server:
  port: 8080

kamis:
  api:
    key: 5a80d6c4-06de-4e55-96ed-baefbd3ace87
    id: 2791
    url: https://www.kamis.or.kr